import { supabase } from '../lib/supabase';

export async function seedDatabase() {
  const brands = [
    { name: 'Zebra', slug: 'zebra', blurb: 'Leader in barcode scanners and mobile computers' },
    { name: 'Honeywell', slug: 'honeywell', blurb: 'Enterprise-grade scanning and mobility solutions' },
    { name: 'Datalogic', slug: 'datalogic', blurb: 'Innovative automatic data capture solutions' },
    { name: 'Epson', slug: 'epson', blurb: 'Reliable receipt and label printing technology' },
    { name: 'Star Micronics', slug: 'star-micronics', blurb: 'Industry-leading POS printers' },
    { name: 'Ingenico', slug: 'ingenico', blurb: 'Secure payment terminal solutions' },
    { name: 'ID TECH', slug: 'id-tech', blurb: 'Innovative payment and identification solutions' },
    { name: 'HP', slug: 'hp', blurb: 'Enterprise computing and POS hardware' },
    { name: 'Elo', slug: 'elo', blurb: 'Commercial touchscreen displays' },
    { name: 'Socket Mobile', slug: 'socket-mobile', blurb: 'Mobile data capture solutions' },
    { name: 'SATO', slug: 'sato', blurb: 'Industrial printing and labeling' },
    { name: 'Seagull Scientific', slug: 'seagull-scientific', blurb: 'BarTender label design software' },
  ];

  const { data: insertedBrands, error: brandError } = await supabase
    .from('brands')
    .upsert(brands, { onConflict: 'slug' })
    .select();

  if (brandError) {
    console.error('Error seeding brands:', brandError);
    return;
  }

  const brandMap = Object.fromEntries(
    insertedBrands.map(b => [b.slug, b.id])
  );

  const products = [
    {
      sku: 'ZEB-DS2208',
      title: 'Zebra DS2208 Handheld Barcode Scanner',
      brand_id: brandMap['zebra'],
      model: 'DS2208',
      short_desc: '2D omnidirectional handheld scanner with superior scan performance',
      long_desc: 'The Zebra DS2208 delivers superior scanning performance on virtually every 1D and 2D barcode. Affordable and versatile, it increases productivity for retail, healthcare, and light industrial applications.',
      msrp: 399.00,
      map_price: 349.00,
      sale_price: 349.00,
      reseller_price: 279.20,
      price_adjustment_type: 'fixed',
      price_adjustment_value: 69.80,
      stock_status: 'In Stock',
      categories: ['barcode-scanners'],
      tags: ['2D', 'handheld', 'corded'],
      specs: {
        'Scan Pattern': '2D Imager',
        'Interface': 'USB',
        'Dimensions': '6.6 x 3.5 x 2.6 in',
        'Weight': '5.6 oz',
      },
      warranty: '3 years',
    },
    {
      sku: 'ZEB-TC22',
      title: 'Zebra TC22 Mobile Computer',
      brand_id: brandMap['zebra'],
      model: 'TC22',
      short_desc: 'Professional-grade Android mobile computer for field workers',
      long_desc: 'The TC22 brings professional-grade reliability, security, and features to everyday mobile computing. Perfect for retail associates, field service technicians, and delivery drivers.',
      msrp: 1599.00,
      map_price: 1449.00,
      sale_price: 1449.00,
      reseller_price: 1159.20,
      price_adjustment_type: 'fixed',
      price_adjustment_value: 289.80,
      stock_status: 'In Stock',
      lead_time_days: 5,
      categories: ['mobile-computers'],
      tags: ['Android', 'rugged', 'WiFi', 'Bluetooth'],
      specs: {
        'Operating System': 'Android 11',
        'Display': '6 inch FHD+',
        'Scanner': 'SE4710 1D/2D',
        'Battery': '4620 mAh',
        'Drop Spec': '5 ft / 1.5 m',
      },
      warranty: '1 year',
    },
    {
      sku: 'ZEB-ZT411',
      title: 'Zebra ZT411 Industrial Printer',
      brand_id: brandMap['zebra'],
      model: 'ZT411',
      short_desc: '4-inch industrial label printer with advanced connectivity',
      long_desc: 'The ZT411 RFID industrial printer provides high-performance printing and encoding in a compact footprint. Ideal for manufacturing, warehousing, and logistics applications.',
      msrp: 2499.00,
      map_price: 0.00,
      sale_price: 0.00,
      reseller_price: 0.00,
      price_adjustment_type: 'fixed',
      price_adjustment_value: 0.00,
      stock_status: 'In Stock',
      categories: ['label-printers'],
      tags: ['industrial', 'RFID', 'thermal'],
      specs: {
        'Print Width': '4 inches',
        'Resolution': '203 dpi',
        'Print Speed': 'Up to 14 ips',
        'Connectivity': 'USB, Serial, Ethernet',
      },
      warranty: '2 years',
    },
    {
      sku: 'HON-1960',
      title: 'Honeywell Xenon Ultra 1960 Scanner',
      brand_id: brandMap['honeywell'],
      model: 'Xenon Ultra 1960',
      short_desc: 'Ultra-rugged cordless 2D scanner with extended range',
      long_desc: 'The Xenon Ultra 1960 brings unparalleled performance and reliability to harsh environments. Features superior scanning technology and an IP65 rating for maximum durability.',
      msrp: 599.00,
      map_price: 529.00,
      sale_price: 529.00,
      reseller_price: 423.20,
      price_adjustment_type: 'fixed',
      price_adjustment_value: 105.80,
      stock_status: 'In Stock',
      categories: ['barcode-scanners'],
      tags: ['2D', 'cordless', 'rugged', 'long-range'],
      specs: {
        'Scan Pattern': '2D Imager',
        'Range': 'Up to 50 ft',
        'Battery': 'Up to 50,000 scans',
        'IP Rating': 'IP65',
      },
      warranty: '3 years',
    },
    {
      sku: 'HON-CT30',
      title: 'Honeywell CT30 XP Mobile Computer',
      brand_id: brandMap['honeywell'],
      model: 'CT30 XP',
      short_desc: 'Full-touch mobile computer for retail and field operations',
      long_desc: 'The CT30 XP combines smartphone simplicity with enterprise-grade performance. Perfect for inventory management, price checks, and mobile POS applications.',
      msrp: 1399.00,
      map_price: 1249.00,
      sale_price: 1249.00,
      reseller_price: 999.20,
      price_adjustment_type: 'fixed',
      price_adjustment_value: 249.80,
      stock_status: 'In Stock',
      categories: ['mobile-computers'],
      tags: ['Android', 'touchscreen', 'WiFi'],
      specs: {
        'Operating System': 'Android 10',
        'Display': '4.0 inch',
        'Scanner': 'N6803 FlexRange',
        'Battery': '4040 mAh',
      },
      warranty: '1 year',
    },
    {
      sku: 'DATA-GD4520',
      title: 'Datalogic Gryphon GD4520 Scanner',
      brand_id: brandMap['datalogic'],
      model: 'Gryphon GD4520',
      short_desc: 'General purpose 2D handheld scanner with white illumination',
      long_desc: 'The Gryphon GD4520 delivers fast and reliable scanning performance. Features white illumination technology that is easier on the eyes during prolonged use.',
      msrp: 329.00,
      map_price: 289.00,
      sale_price: 289.00,
      reseller_price: 231.20,
      price_adjustment_type: 'fixed',
      price_adjustment_value: 57.80,
      stock_status: 'In Stock',
      categories: ['barcode-scanners'],
      tags: ['2D', 'handheld', 'retail'],
      specs: {
        'Scan Pattern': '2D Imager',
        'Interface': 'USB, Keyboard Wedge',
        'Read Range': 'Up to 19 inches',
        'Illumination': 'White LED',
      },
      warranty: '3 years',
    },
    {
      sku: 'EPS-TM88VII',
      title: 'Epson TM-T88VII Receipt Printer',
      brand_id: brandMap['epson'],
      model: 'TM-T88VII',
      short_desc: 'High-performance thermal receipt printer with enhanced connectivity',
      long_desc: 'The TM-T88VII is the latest generation of Epson\'s industry-leading receipt printer family. Features fast printing, multiple connectivity options, and paper-saving technology.',
      msrp: 599.00,
      map_price: 529.00,
      sale_price: 529.00,
      reseller_price: 423.20,
      price_adjustment_type: 'fixed',
      price_adjustment_value: 105.80,
      stock_status: 'In Stock',
      categories: ['receipt-printers'],
      tags: ['thermal', 'USB', 'Ethernet', 'retail'],
      specs: {
        'Print Speed': 'Up to 500mm/sec',
        'Paper Width': '80mm',
        'Connectivity': 'USB, Ethernet, Bluetooth',
        'Auto-Cutter': 'Yes',
      },
      warranty: '3 years',
    },
    {
      sku: 'STAR-TSP143',
      title: 'Star Micronics TSP143IIIBI Receipt Printer',
      brand_id: brandMap['star-micronics'],
      model: 'TSP143IIIBI',
      short_desc: 'Bluetooth receipt printer for mobile POS applications',
      long_desc: 'The TSP143IIIBI combines high-speed printing with wireless Bluetooth connectivity. Perfect for tablet-based POS systems and mobile applications.',
      msrp: 399.00,
      map_price: 349.00,
      sale_price: 349.00,
      reseller_price: 279.20,
      price_adjustment_type: 'fixed',
      price_adjustment_value: 69.80,
      stock_status: 'In Stock',
      categories: ['receipt-printers'],
      tags: ['thermal', 'Bluetooth', 'mobile', 'retail'],
      specs: {
        'Print Speed': '250mm/sec',
        'Paper Width': '80mm',
        'Connectivity': 'Bluetooth',
        'Auto-Cutter': 'Yes',
      },
      warranty: '2 years',
    },
    {
      sku: 'ING-LANE7K',
      title: 'Ingenico Lane/7000 Payment Terminal',
      brand_id: brandMap['ingenico'],
      model: 'Lane/7000',
      short_desc: 'All-in-one smart payment terminal for retail',
      long_desc: 'The Lane/7000 delivers a seamless payment experience with support for all payment types including contactless, chip, and swipe. Features a large touchscreen for customer engagement.',
      msrp: 899.00,
      map_price: 0.00,
      sale_price: 0.00,
      reseller_price: 0.00,
      price_adjustment_type: 'fixed',
      price_adjustment_value: 0.00,
      stock_status: 'In Stock',
      lead_time_days: 7,
      categories: ['card-readers-and-payments'],
      tags: ['EMV', 'NFC', 'contactless', 'retail'],
      specs: {
        'Display': '5 inch touchscreen',
        'Payment Types': 'EMV, NFC, Magstripe',
        'Connectivity': 'Ethernet, WiFi',
        'Security': 'PCI PTS 5.x',
      },
      warranty: '1 year',
    },
    {
      sku: 'IDTECH-AUGUSTA',
      title: 'ID TECH Augusta S Payment Terminal',
      brand_id: brandMap['id-tech'],
      model: 'Augusta S',
      short_desc: 'Compact EMV and NFC payment device',
      long_desc: 'The Augusta S combines small size with powerful features. Accepts all payment types and connects via USB for simple integration.',
      msrp: 249.00,
      map_price: 219.00,
      sale_price: 219.00,
      reseller_price: 175.20,
      price_adjustment_type: 'fixed',
      price_adjustment_value: 43.80,
      stock_status: 'In Stock',
      categories: ['card-readers-and-payments'],
      tags: ['EMV', 'NFC', 'USB', 'compact'],
      specs: {
        'Payment Types': 'EMV, NFC, Magstripe',
        'Interface': 'USB',
        'Dimensions': '3.7 x 3.0 x 1.8 in',
        'Weight': '6 oz',
      },
      warranty: '1 year',
    },
    {
      sku: 'ELO-1502L',
      title: 'Elo 1502L 15-inch Touchscreen Monitor',
      brand_id: brandMap['elo'],
      model: '1502L',
      short_desc: 'Professional-grade touchscreen display for POS',
      long_desc: 'The Elo 1502L delivers reliable touch performance in a sleek, space-saving design. Features IntelliTouch surface acoustic wave technology for superior accuracy.',
      msrp: 599.00,
      map_price: 529.00,
      sale_price: 529.00,
      reseller_price: 423.20,
      price_adjustment_type: 'fixed',
      price_adjustment_value: 105.80,
      stock_status: 'In Stock',
      categories: ['touch-displays'],
      tags: ['touchscreen', '15-inch', 'POS', 'retail'],
      specs: {
        'Display Size': '15.6 inches',
        'Resolution': '1366 x 768',
        'Touch Technology': 'IntelliTouch SAW',
        'Connectivity': 'VGA, HDMI, USB',
      },
      warranty: '3 years',
    },
    {
      sku: 'ELO-2202L',
      title: 'Elo 2202L 22-inch Touchscreen Monitor',
      brand_id: brandMap['elo'],
      model: '2202L',
      short_desc: 'Wide-format touchscreen display for customer-facing applications',
      long_desc: 'The Elo 2202L provides an immersive experience for self-service kiosks and customer-facing applications. Features edge-to-edge glass design and commercial-grade reliability.',
      msrp: 899.00,
      map_price: 799.00,
      sale_price: 799.00,
      reseller_price: 639.20,
      price_adjustment_type: 'fixed',
      price_adjustment_value: 159.80,
      stock_status: 'In Stock',
      categories: ['touch-displays'],
      tags: ['touchscreen', '22-inch', 'widescreen', 'kiosk'],
      specs: {
        'Display Size': '21.5 inches',
        'Resolution': '1920 x 1080',
        'Touch Technology': 'IntelliTouch Pro PCAP',
        'Connectivity': 'HDMI, DisplayPort, USB',
      },
      warranty: '3 years',
    },
  ];

  const { error: productError } = await supabase
    .from('products')
    .upsert(products, { onConflict: 'sku' });

  if (productError) {
    console.error('Error seeding products:', productError);
    return;
  }

  console.log('Database seeded successfully!');
  console.log(`Created ${brands.length} brands and ${products.length} products`);
}
